
# Androguard is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Androguard is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Androguard.  If not, see <http://www.gnu.org/licenses/>.

# frameworks/base/core/res/AndroidManifest.xml

# This list is also updated periodically with scripts/update_android_permissions.py
# ######################################### PERMISSIONS ###################
# flake8: noqa
DVM_PERMISSIONS = {
    'MANIFEST_PERMISSION': {
        'SEND_SMS': ['dangerous', '发送短信', '允许应用发送短信。恶意应用可能在未经您确认的情况下发送短信，造成经济损失。'],
        'SEND_SMS_NO_CONFIRMATION': ['dangerous', '发送短信', '通过短信应用发送短信，无需用户输入或确认。'],
        'CALL_PHONE': ['dangerous', '直接拨打电话号码', '允许应用直接拨打电话号码而无需您介入。恶意应用可能导致意外通话并产生话费。请注意，此权限不允许应用拨打紧急号码。'],
        'RECEIVE_SMS': ['dangerous', '接收短信', '允许应用接收和处理短信。恶意应用可能监控或删除您的短信而不告知您。'],
        'RECEIVE_MMS': ['dangerous', '接收彩信', '允许应用接收和处理彩信。恶意应用可能监控或删除您的彩信而不告知您。'],
        'READ_SMS': ['dangerous', '读取短信或彩信', '允许应用读取手机或 SIM 卡上存储的短信。恶意应用可能读取您的机密信息。'],
        'WRITE_SMS': ['dangerous', '编辑短信或彩信', '允许应用写入手机或 SIM 卡上存储的短信。恶意应用可能删除您的短信。'],
        'RECEIVE_WAP_PUSH': ['dangerous', '接收 WAP 推送', '允许应用接收和处理 WAP 推送消息。恶意应用可能监控或删除您的消息而不告知您。'],
        'READ_CONTACTS': ['dangerous', '读取联系人数据', '允许应用读取手机上存储的所有联系人数据。恶意应用可利用此权限将您的数据发送给其他人。'],
        'WRITE_CONTACTS': ['dangerous', '修改联系人数据', '允许应用修改手机上存储的联系人数据。恶意应用可利用此权限擦除或修改您的联系人信息。'],
        'READ_PROFILE': ['dangerous', '读取用户的个人资料', '允许应用读取用户的个人资料数据。'],
        'WRITE_PROFILE': ['dangerous', '修改用户的个人资料', '允许应用写入（但不能读取）用户的个人资料数据。'],
        'READ_SOCIAL_STREAM': ['dangerous', '读取用户的社交信息流', '允许应用读取用户的社交信息流。'],
        'WRITE_SOCIAL_STREAM': ['dangerous', '修改用户的社交信息流', '允许应用写入（但不能读取）用户的社交信息流数据。'],
        'READ_CALENDAR': ['dangerous', '读取日历事件', '允许应用读取手机上存储的所有日历事件。恶意应用可利用此权限将您的日历事件发送给其他人。'],
        'WRITE_CALENDAR': ['dangerous', '添加或修改日历事件并向参与者发送邮件', '允许应用添加或修改日历上的事件，可能会向参与者发送邮件。恶意应用可利用此权限擦除或修改您的日历事件或向参与者发送邮件。'],
        'READ_USER_DICTIONARY': ['dangerous', '读取用户自定义词典', '允许应用读取用户词典中存储的任何私密词汇、姓名和短语。'],
        'WRITE_USER_DICTIONARY': ['normal', '写入用户自定义词典', '允许应用向用户词典中添加新词。'],
        'READ_HISTORY_BOOKMARKS': ['dangerous', '读取浏览器的历史记录和书签', '允许应用读取浏览器访问过的所有 URL 以及浏览器的所有书签。'],
        'WRITE_HISTORY_BOOKMARKS': ['dangerous', '修改浏览器的历史记录和书签', '允许应用修改手机上存储的浏览器历史记录或书签。恶意应用可利用此权限擦除或修改您的浏览器数据。'],
        'SET_ALARM': ['normal', '在闹钟中设置闹钟', '允许应用在已安装的闹钟应用中设置闹钟。某些闹钟应用可能未实现此功能。'],
        'ACCESS_FINE_LOCATION': ['dangerous', '精确（GPS）位置', '访问精确位置来源，例如手机的全球定位系统（GPS）（如可用）。恶意应用可利用此权限确定您的位置，并可能消耗更多电池电量。'],
        'ACCESS_COARSE_LOCATION': ['dangerous', '粗略（基于网络的）位置', '访问粗略位置来源，例如移动网络数据库，以确定大概的手机位置（如可用）。恶意应用可利用此权限确定您的大致位置。'],
        'ACCESS_MOCK_LOCATION': ['dangerous', '用于测试的模拟位置源', '创建用于测试的模拟位置源。恶意应用可利用此权限覆盖 GPS 或网络提供商等真实位置源所返回的位置和/或状态。'],
        'ACCESS_LOCATION_EXTRA_COMMANDS': ['normal', '访问额外的位置提供者命令', '访问额外的位置提供者命令。恶意应用可利用此权限干扰 GPS 或其他位置源的运行。'],
        'INSTALL_LOCATION_PROVIDER': ['signatureOrSystem', '安装位置提供者的权限', '创建用于测试的模拟位置源。恶意应用可利用此权限覆盖 GPS 或网络提供商等真实位置源所返回的位置和/或状态，或监控并向外部报告您的位置。'],
        'INTERNET': ['normal', '完全的互联网访问', '允许应用创建网络套接字。'],
        'ACCESS_NETWORK_STATE': ['normal', '查看网络状态', '允许应用查看所有网络的状态。'],
        'ACCESS_WIFI_STATE': ['normal', '查看 Wi-Fi 状态', '允许应用查看 Wi-Fi 状态的相关信息。'],
        'BLUETOOTH': ['normal', '创建蓝牙连接', '允许应用连接已配对的蓝牙设备。'],
        'NFC': ['normal', '控制近场通信（NFC）', '允许应用与近场通信（NFC）标签、卡片和读卡器进行通信。'],
        'USE_SIP': ['dangerous', '拨打/接听互联网电话', '允许应用使用 SIP 服务拨打或接听互联网电话。'],
        'ACCOUNT_MANAGER': ['signature', '充当账户管理服务', '允许应用调用账户身份验证器。'],
        'GET_ACCOUNTS': ['dangerous', '列出账户', '允许访问账户服务中的账户列表。'],
        'AUTHENTICATE_ACCOUNTS': ['dangerous', '充当账户身份验证器', '允许应用使用账户管理器的账户身份验证功能，包括创建账户以及获取和设置其密码。'],
        'USE_CREDENTIALS': ['dangerous', '使用账户的身份验证凭据', '允许应用请求身份验证令牌。'],
        'MANAGE_ACCOUNTS': ['dangerous', '管理账户列表', '允许应用执行添加和删除账户以及删除其密码等操作。'],
        'MODIFY_AUDIO_SETTINGS': ['normal', '更改音频设置', '允许应用修改全局音频设置，例如音量和路由。'],
        'RECORD_AUDIO': ['dangerous', '录制音频', '允许应用访问音频录制路径。'],
        'CAMERA': ['dangerous', '拍摄照片和视频', '允许应用使用相机拍摄照片和视频。这意味着应用可随时收集相机所看到的画面。'],
        'VIBRATE': ['normal', '控制振动器', '允许应用控制振动器。'],
        'FLASHLIGHT': ['normal', '控制闪光灯', '允许应用控制闪光灯。'],
        'ACCESS_USB': ['signatureOrSystem', '访问 USB 设备', '允许应用访问 USB 设备。'],
        'HARDWARE_TEST': ['signature', '测试硬件', '允许应用控制各种外围设备以进行硬件测试。'],
        'PROCESS_OUTGOING_CALLS': ['dangerous', '拦截拨出电话', '允许应用处理拨出电话并更改要拨打的号码。恶意应用可能监控、转接或阻止拨出电话。'],
        'MODIFY_PHONE_STATE': ['signatureOrSystem', '修改手机状态', '允许应用控制设备的电话功能。具有此权限的应用可在不通知您的情况下切换网络、打开或关闭电话无线电等。'],
        'READ_PHONE_STATE': ['dangerous', '读取手机状态和身份', '允许应用访问设备的电话功能。具有此权限的应用可以获取本机电话号码和序列号、判断当前是否有通话以及通话连接到的号码等信息。'],
        'WRITE_EXTERNAL_STORAGE': ['dangerous', '读取/修改/删除外部存储内容', '允许应用写入外部存储。'],
        'READ_EXTERNAL_STORAGE': ['dangerous', '读取外部存储内容', '允许应用从外部存储读取数据。'],
        'WRITE_SETTINGS': ['dangerous', '修改全局系统设置', '允许应用修改系统的设置数据。恶意应用可能损坏您的系统配置。'],
        'WRITE_SECURE_SETTINGS': ['signatureOrSystem', '修改安全系统设置', '允许应用修改系统的安全设置数据。不供普通应用使用。'],
        'WRITE_GSERVICES': ['signatureOrSystem', '修改 Google 服务地图', '允许应用修改 Google 服务地图。不供普通应用使用。'],
        'EXPAND_STATUS_BAR': ['normal', '展开/收起状态栏', '允许应用展开或收起状态栏。'],
        'GET_TASKS': ['dangerous', '获取正在运行的应用', '允许应用获取当前和最近运行的任务信息。可能允许恶意应用发现其他应用的隐私信息。'],
        'REORDER_TASKS': ['normal', '调整正在运行的应用的顺序', '允许应用将任务移到前台或后台。恶意应用可在您不知情的情况下强制显示在前台。'],
        'CHANGE_CONFIGURATION': ['signatureOrSystem', '更改 UI 设置', '允许应用更改当前配置，例如语言环境或整体字体大小。'],
        'RESTART_PACKAGES': ['normal', '终止后台进程', '允许应用终止其他应用的后台进程，即使内存并不紧张。'],
        'KILL_BACKGROUND_PROCESSES': ['normal', '终止后台进程', '允许应用终止其他应用的后台进程，即使内存并不紧张。'],
        'FORCE_STOP_PACKAGES': ['signature', '强制停止其他应用', '允许应用强制停止其他应用。'],
        'DUMP': ['signatureOrSystem', '获取系统内部状态', '允许应用获取系统的内部状态。恶意应用可能获取各种其通常不应需要的私密和敏感信息。'],
        'SYSTEM_ALERT_WINDOW': ['dangerous', '显示系统级警告', '允许应用显示系统级警告窗口。恶意应用可以接管手机整个屏幕。'],
        'SET_ANIMATION_SCALE': ['dangerous', '修改全局动画速度', '允许应用随时更改全局动画速度（加快或减慢动画）。'],
        'PERSISTENT_ACTIVITY': ['dangerous', '使应用始终运行', '允许应用将自身部分设为持续运行，使系统无法将这些资源用于其他应用。'],
        'GET_PACKAGE_SIZE': ['normal', '测量应用占用的存储空间', '允许应用获取任何包所占用的存储空间。'],
        'SET_PREFERRED_APPLICATIONS': ['signature', '设置首选应用', '允许应用修改您的首选应用。恶意应用可借此在您不知情的情况下更改要运行的应用，伪装您现有的应用以收集您的私人数据。'],
        'RECEIVE_BOOT_COMPLETED': ['normal', '开机时自动启动', '允许应用在系统启动完成后立即自启。这可能会使手机启动变慢，并因应用始终运行而降低手机的运行速度。'],
        'BROADCAST_STICKY': ['normal', '发送粘性广播', '允许应用发送粘性广播——广播结束后仍会保留。恶意应用可能使手机消耗过多内存，导致手机变慢或不稳定。'],
        'WAKE_LOCK': ['normal', '防止手机进入休眠', '允许应用阻止手机进入休眠状态。'],
        'SET_WALLPAPER': ['normal', '设置壁纸', '允许应用设置系统壁纸。'],
        'SET_WALLPAPER_HINTS': ['normal', '设置壁纸尺寸提示', '允许应用设置系统壁纸的尺寸提示。'],
        'SET_TIME': ['signatureOrSystem', '设置时间', '允许应用更改手机时钟。'],
        'SET_TIME_ZONE': ['signatureOrSystem', '设置时区', '允许应用更改手机时区。'],
        'MOUNT_UNMOUNT_FILESYSTEMS': ['dangerous', '挂载和卸载文件系统', '允许应用挂载和卸载可移动存储的文件系统。'],
        'MOUNT_FORMAT_FILESYSTEMS': ['dangerous', '格式化外部存储', '允许应用格式化可移动存储。'],
        'ASEC_ACCESS': ['signature', '获取内部存储信息', '允许应用获取内部存储的相关信息。'],
        'ASEC_CREATE': ['signature', '创建内部存储', '允许应用创建内部存储。'],
        'ASEC_DESTROY': ['signature', '销毁内部存储', '允许应用销毁内部存储。'],
        'ASEC_MOUNT_UNMOUNT': ['signature', '挂载/卸载内部存储', '允许应用挂载/卸载内部存储。'],
        'ASEC_RENAME': ['signature', '重命名内部存储', '允许应用重命名内部存储。'],
        'DISABLE_KEYGUARD': ['normal', '关闭锁屏', '允许应用在锁屏不安全的条件下关闭锁屏。'],
        'READ_SYNC_SETTINGS': ['normal', '读取同步设置', '允许应用读取同步设置，例如联系人是否启用了同步。'],
        'WRITE_SYNC_SETTINGS': ['normal', '修改同步设置', '允许应用修改同步设置，例如联系人是否启用了同步。'],
        'READ_SYNC_STATS': ['normal', '读取同步统计', '允许应用读取同步统计信息，例如已发生的同步历史。'],
        'WRITE_APN_SETTINGS': ['dangerous', '修改接入点名称（APN）设置', '允许应用修改 APN 设置，例如任何 APN 的代理和端口。'],
        'SUBSCRIBED_FEEDS_READ': ['normal', '读取已订阅的 Feed', '允许应用获取当前已同步 Feed 的详细信息。'],
        'SUBSCRIBED_FEEDS_WRITE': ['dangerous', '修改已订阅的 Feed', '允许应用修改您当前已同步的 Feed。恶意应用可借此更改您的同步 Feed。'],
        'CHANGE_NETWORK_STATE': ['normal', '更改网络连接状态', '允许应用更改网络连接状态。'],
        'CHANGE_WIFI_STATE': ['normal', '更改 Wi-Fi 状态', '允许应用连接和断开 Wi-Fi 接入点，并修改已配置的 Wi-Fi 网络。'],
        'CHANGE_WIFI_MULTICAST_STATE': ['normal', '允许接收 Wi-Fi 组播数据包', '允许应用接收并非直接发送到您设备的数据包。在发现附近提供的服务时这非常有用，但比非组播模式消耗更多电量。'],
        'BLUETOOTH_ADMIN': ['normal', '蓝牙管理', '允许应用发现并配对蓝牙设备。'],
        'CLEAR_APP_CACHE': ['signatureOrSystem', '删除所有应用缓存数据', '允许应用通过删除应用缓存目录中的文件来释放手机存储空间。此访问通常仅限于系统进程。'],
        'READ_LOGS': ['dangerous', '读取敏感日志数据', '允许应用读取系统的各种日志文件。这使其能够发现您使用手机的一般信息，可能包括个人或隐私信息。'],
        'SET_DEBUG_APP': ['dangerous', '启用应用调试', '允许应用为其他应用开启调试。恶意应用可利用此权限杀死其他应用。'],
        'SET_PROCESS_LIMIT': ['dangerous', '限制运行进程的数量', '允许应用控制将运行的最大进程数。普通应用通常不需要此权限。'],
        'SET_ALWAYS_FINISH': ['dangerous', '使所有后台应用关闭', '允许应用控制是否在 Activity 进入后台后立即将其结束。普通应用通常不需要此权限。'],
        'SIGNAL_PERSISTENT_PROCESSES': ['dangerous', '向应用发送 Linux 信号', '允许应用请求将所提供的信号发送给所有持久性进程。'],
        'DIAGNOSTIC': ['signature', '读取/写入 diag 组拥有的资源', '允许应用读取和写入 diag 组拥有的任何资源，例如 /dev 中的文件。这可能会影响系统稳定性和安全性。该权限仅应由制造商或运营商用于特定硬件的诊断。'],
        'STATUS_BAR': ['signatureOrSystem', '禁用或修改状态栏', '允许应用禁用状态栏或添加和移除系统图标。'],
        'STATUS_BAR_SERVICE': ['signature', '状态栏', '允许应用充当状态栏。'],
        'FORCE_BACK': ['signature', '强制应用关闭', '允许应用强制关闭并返回任何前台 Activity。普通应用通常不需要此权限。'],
        'UPDATE_DEVICE_STATS': ['signatureOrSystem', '修改电池统计', '允许修改已收集的电池统计信息。不供普通应用使用。'],
        'INTERNAL_SYSTEM_WINDOW': ['signature', '显示未经授权的窗口', '允许创建供内部系统用户界面使用的窗口。不供普通应用使用。'],
        'MANAGE_APP_TOKENS': ['signature', '管理应用令牌', '允许应用创建和管理自己的令牌，绕过常规的 Z 轴排序。普通应用通常不需要此权限。'],
        'INJECT_EVENTS': ['signature', '按键和控制按钮', '允许应用将自己的输入事件（如按键）发送给其他应用。恶意应用可借此控制手机。'],
        'SET_ACTIVITY_WATCHER': ['signature', '监控并控制所有应用启动', '允许应用监控并控制系统启动 Activity 的方式。恶意应用可能完全破坏系统。此权限仅供开发使用，普通手机使用场景不需要。'],
        'SHUTDOWN': ['signature', '部分关机', '将 Activity 管理器置于关闭状态。不会执行完全关机。'],
        'STOP_APP_SWITCHES': ['signature', '阻止应用切换', '阻止用户切换到其他应用。'],
        'READ_INPUT_STATE': ['signature', '记录您的按键和操作', '允许应用监听您按下的按键，即使您正在与其他应用交互（如输入密码）。普通应用通常不需要此权限。'],
        'BIND_INPUT_METHOD': ['signature', '绑定到输入法', '允许持有者绑定到输入法的顶层接口。普通应用通常不需要此权限。'],
        'BIND_WALLPAPER': ['signatureOrSystem', '绑定到壁纸', '允许持有者绑定到壁纸的顶层接口。普通应用通常不需要此权限。'],
        'BIND_DEVICE_ADMIN': ['signature', '与设备管理员交互', '允许持有者向设备管理员发送 Intent。普通应用通常不需要此权限。'],
        'SET_ORIENTATION': ['signature', '更改屏幕方向', '允许应用随时更改屏幕旋转。普通应用通常不需要此权限。'],
        'INSTALL_PACKAGES': ['signatureOrSystem', '直接安装应用', '允许应用安装新的或更新的 Android 包。恶意应用可借此添加具有任意强大权限的新应用。'],
        'REQUEST_INSTALL_PACKAGES': ['dangerous', '允许应用请求安装软件包', '允许应用请求安装软件包。恶意应用可借此试图诱骗用户安装其他恶意软件包。'],
        'CLEAR_APP_USER_DATA': ['signature', '删除其他应用的数据', '允许应用清除用户数据。'],
        'DELETE_CACHE_FILES': ['signatureOrSystem', '删除其他应用的缓存', '允许应用删除缓存文件。'],
        'DELETE_PACKAGES': ['signatureOrSystem', '删除应用', '允许应用删除 Android 包。恶意应用可借此删除重要应用。'],
        'MOVE_PACKAGE': ['signatureOrSystem', '移动应用资源', '允许应用在内部和外部存储之间移动应用资源。'],
        'CHANGE_COMPONENT_ENABLED_STATE': ['signatureOrSystem', '启用或禁用应用组件', '允许应用更改其他应用的组件是否启用。恶意应用可借此禁用手机的重要功能。使用此权限时需小心，因为可能使应用组件进入不可用、不一致或不稳定的状态。'],
        'ACCESS_SURFACE_FLINGER': ['signature', '访问 SurfaceFlinger', '允许应用使用 SurfaceFlinger 的底层功能。'],
        'READ_FRAME_BUFFER': ['signature', '读取帧缓冲区', '允许应用读取帧缓冲区的内容。'],
        'BRICK': ['signature', '永久禁用手机', '允许应用永久禁用整部手机。这是非常危险的权限。'],
        'REBOOT': ['signatureOrSystem', '强制重启手机', '允许应用强制手机重启。'],
        'DEVICE_POWER': ['signature', '开关手机', '允许应用开关手机。'],
        'FACTORY_TEST': ['signature', '在工厂测试模式下运行', '以底层制造商测试方式运行，允许完全访问手机硬件。仅在手机运行于制造商测试模式时可用。'],
        'BROADCAST_PACKAGE_REMOVED': ['signature', '发送软件包已移除的广播', '允许应用广播应用包已被移除的通知。恶意应用可借此终止其他正在运行的应用。'],
        'BROADCAST_SMS': ['signature', '发送短信已接收的广播', '允许应用广播已接收到 SMS 消息的通知。恶意应用可借此伪造收到的短信。'],
        'BROADCAST_WAP_PUSH': ['signature', '发送 WAP-PUSH 已接收的广播', '允许应用广播已接收到 WAP-PUSH 消息的通知。恶意应用可借此伪造彩信接收或将任意网页的内容静默替换为恶意变体。'],
        'MASTER_CLEAR': ['signatureOrSystem', '将系统恢复出厂设置', '允许应用将系统完全恢复出厂设置，擦除所有数据、配置和已安装的应用。'],
        'CALL_PRIVILEGED': ['signatureOrSystem', '直接拨打任何电话号码', '允许应用直接拨打任何电话号码（包括紧急号码）而无需您介入。恶意应用可能向紧急服务拨打不必要的非法电话。'],
        'PERFORM_CDMA_PROVISIONING': ['signatureOrSystem', '直接启动 CDMA 手机设置', '允许应用启动 CDMA 配置。恶意应用可借此不必要地启动 CDMA 配置。'],
        'CONTROL_LOCATION_UPDATES': ['signatureOrSystem', '控制位置更新通知', '允许启用/禁用来自无线电的位置更新通知。不供普通应用使用。'],
        'ACCESS_CHECKIN_PROPERTIES': ['signatureOrSystem', '访问 check-in 属性', '允许读/写访问由 check-in 服务上传的属性。不供普通应用使用。'],
        'PACKAGE_USAGE_STATS': ['signature', '更新组件使用统计', '允许修改已收集的组件使用统计信息。不供普通应用使用。'],
        'BATTERY_STATS': ['signature', '修改电池统计', '允许修改已收集的电池统计信息。不供普通应用使用。'],
        'BACKUP': ['signatureOrSystem', '控制系统备份和恢复', '允许应用控制系统的备份和恢复机制。不供普通应用使用。'],
        'BIND_APPWIDGET': ['signatureOrSystem', '选择小部件', '允许应用告知系统哪些小部件可被哪些应用使用。具有此权限的应用可将个人数据访问权限授予其他应用。不供普通应用使用。'],
        'CHANGE_BACKGROUND_DATA_SETTING': ['signature', '更改后台数据使用设置', '允许应用更改后台数据使用设置。'],
        # Short descriptions are generated by ChatGPT, so they may not be accurate.
        'GLOBAL_SEARCH': ['signatureOrSystem', '允许全局搜索系统访问提供者的数据。', '此权限可用于内容提供者，以允许全局搜索系统访问其数据。通常在提供者受到某些权限保护（而全局搜索不应持有这些权限）时使用，并作为只读权限添加到提供者中执行全局搜索查询的路径。此权限不能由普通应用持有；它由应用用来保护自身免受全局搜索以外其他访问的影响。'],
        'GLOBAL_SEARCH_CONTROL': ['signature', '没有指定角色或功能的权限。', '没有指定角色或功能的权限。'],
        'SET_WALLPAPER_COMPONENT': ['signatureOrSystem', '允许设置壁纸组件。', '允许设置壁纸组件。'],
        'ACCESS_CACHE_FILESYSTEM': ['signatureOrSystem', '访问缓存文件系统', '允许应用读写缓存文件系统。'],
        'COPY_PROTECTED_DATA': ['signature', '允许调用默认容器服务来复制内容。不供普通应用使用。', '允许调用默认容器服务来复制内容。不供普通应用使用。'],
        'C2D_MESSAGE': ['signature', '允许云到设备消息传递', '允许应用接收推送通知。'],
        'ADD_VOICEMAIL': ['dangerous', '向系统中添加语音邮件', '允许应用向系统中添加语音邮件。'],
        'ACCEPT_HANDOVER': ['dangerous', '允许通话应用继续在另一个应用中开始的通话。', '允许通话应用继续另一个应用中已开始的通话。例如：视频通话应用希望继续通过用户移动网络进行的语音通话。'],
        'ACCESS_NOTIFICATION_POLICY': ['normal', '用于访问通知策略的标记权限。', '希望访问通知策略的应用的标记权限。'],
        'ANSWER_PHONE_CALLS': ['dangerous', '允许应用接听来电。', '允许应用接听来电。'],
        'BIND_ACCESSIBILITY_SERVICE': ['signature', '无障碍服务进行系统绑定所需。', '无障碍服务必须要求此权限，以确保只有系统可以绑定到它。'],
        'BIND_AUTOFILL_SERVICE': ['signature', '自动填充服务进行系统绑定所需。', '自动填充服务必须要求此权限，以确保只有系统可以绑定到它。'],
        'BIND_CARRIER_MESSAGING_SERVICE': ['signature', '用于绑定到运营商消息服务的系统级权限。', '允许绑定到运营商应用中服务的系统进程将具有此权限。'],
        'BIND_CARRIER_SERVICES': ['signature', '用于绑定到运营商服务的系统级权限。', '允许绑定到运营商应用中服务的系统进程将具有此权限。运营商应用应使用此权限来保护只允许系统绑定的服务。'],
        'BIND_CHOOSER_TARGET_SERVICE': ['signature', '选择器目标服务进行系统绑定所需。', '选择器目标服务必须要求此权限，以确保只有系统可以绑定到它。'],
        'BIND_CONDITION_PROVIDER_SERVICE': ['signature', '条件提供者服务进行系统绑定所需。', '条件提供者服务必须要求此权限，以确保只有系统可以绑定到它。'],
        'BIND_DREAM_SERVICE': ['signature', '梦境服务进行系统绑定所需。', '梦境服务必须要求此权限，以确保只有系统可以绑定到它。'],
        'BIND_INCALL_SERVICE': ['signature', '通话服务进行系统绑定所需。', '通话服务必须要求此权限，以确保只有系统可以绑定到它。'],
        'BIND_MIDI_DEVICE_SERVICE': ['signature', 'MIDI 设备服务进行系统绑定所需。', 'MIDI 设备服务必须要求此权限，以确保只有系统可以绑定到它。'],
        'BIND_NFC_SERVICE': ['signature', '系统绑定到 NFC 服务所需。', 'HostApduService 或 OffHostApduService 必须要求此权限，以确保只有系统可以绑定到它。'],
        'BIND_NOTIFICATION_LISTENER_SERVICE': ['signature', '通知监听服务进行系统绑定所需。', '通知监听服务必须要求此权限，以确保只有系统可以绑定到它。'],
        'BIND_PRINT_SERVICE': ['signature', '打印服务进行系统绑定所需。', '打印服务必须要求此权限，以确保只有系统可以绑定到它。'],
        'BIND_QUICK_SETTINGS_TILE': ['signatureOrSystem', '允许绑定到第三方快捷设置磁贴。', '允许应用绑定到第三方快捷设置磁贴。'],
        'BIND_REMOTEVIEWS': ['signature', '远程视图服务进行系统绑定所需。', '远程视图服务必须要求此权限，以确保只有系统可以绑定到它。'],
        'BIND_SCREENING_SERVICE': ['signature', '电话筛选服务进行系统绑定所需。', '电话筛选服务必须要求此权限，以确保只有系统可以绑定到它。'],
        'BIND_TELECOM_CONNECTION_SERVICE': ['signature', '连接服务进行系统绑定所需。', '连接服务必须要求此权限，以确保只有系统可以绑定到它。'],
        'BIND_TEXT_SERVICE': ['signature', '文本服务（如拼写检查器服务）进行系统绑定所需。', '文本服务（如 SpellCheckerService）必须要求此权限，以确保只有系统可以绑定到它。'],
        'BIND_TV_INPUT': ['signature', '电视输入服务进行系统绑定所需。', '电视输入服务必须要求此权限，以确保只有系统可以绑定到它。'],
        'BIND_VISUAL_VOICEMAIL_SERVICE': ['signature', '可视语音邮件服务进行系统绑定所需。', '可视语音邮件服务必须要求此权限，以确保只有系统可以绑定到它。'],
        'BIND_VOICE_INTERACTION': ['signature', '语音交互服务进行系统绑定所需。', '语音交互服务必须要求此权限，以确保只有系统可以绑定到它。'],
        'BIND_VPN_SERVICE': ['signature', 'VPN 服务进行系统绑定所需。', 'VPN 服务必须要求此权限，以确保只有系统可以绑定到它。'],
        'BIND_VR_LISTENER_SERVICE': ['signature', 'VR 监听服务进行系统绑定所需。', 'VR 监听服务必须要求此权限，以确保只有系统可以绑定到它。'],
        'BLUETOOTH_PRIVILEGED': ['signatureOrSystem', '允许在无需用户交互的情况下执行特权蓝牙操作。', '允许应用在无需用户交互的情况下配对蓝牙设备，并允许或禁止电话簿访问或消息访问。第三方应用不可使用。'],
        'BODY_SENSORS': ['dangerous', '授予对身体传感器（如心率）的访问权限。', '允许应用访问用户用于测量身体内部状况的传感器数据，如心率。'],
        'CAPTURE_AUDIO_OUTPUT': ['signatureOrSystem', '允许捕获音频输出。', '允许应用捕获音频输出。'],
        'CAPTURE_SECURE_VIDEO_OUTPUT': ['normal', '允许捕获安全视频输出。', '允许应用捕获安全视频输出。'],
        'CAPTURE_VIDEO_OUTPUT': ['normal', '允许捕获视频输出。', '允许应用捕获视频输出。'],
        'FOREGROUND_SERVICE': ['normal', '允许普通应用使用 Service.startForeground。', '允许普通应用使用 Service.startForeground。'],
        'GET_ACCOUNTS_PRIVILEGED': ['signatureOrSystem', '授予访问账户服务的权限。', '允许访问账户服务中的账户列表。'],
        'INSTALL_SHORTCUT': ['normal', '允许在启动器中安装快捷方式。', '允许应用在启动器中安装快捷方式。'],
        'INSTANT_APP_FOREGROUND_SERVICE': ['signatureOrSystem', '允许即时应用创建前台服务。', '允许即时应用创建前台服务。'],
        'LOCATION_HARDWARE': ['normal', '允许使用硬件中的位置功能。', '允许应用使用硬件中的位置功能，例如地理围栏 API。'],
        'MANAGE_DOCUMENTS': ['signature', '允许管理文档访问（通常在选择器中）。', '允许应用管理对文档的访问权限，通常作为文档选择器的一部分。'],
        'MANAGE_OWN_CALLS': ['normal', '允许通话应用管理其自己的通话。', '允许通过自管理的 ConnectionService API 管理其自身通话的通话应用。'],
        'MEDIA_CONTENT_CONTROL': ['normal', '允许控制媒体内容的播放。', '允许应用了解正在播放的内容并控制其播放。'],
        'NFC_TRANSACTION_EVENT': ['normal', '允许接收 NFC 交易事件。', '允许应用接收 NFC 交易事件。'],
        'READ_CALL_LOG': ['dangerous', '授予对用户通话记录读取权限。', '允许应用读取用户的通话记录。'],
        'READ_PHONE_NUMBERS': ['dangerous', '允许读取设备的电话号码。', '允许读取设备的电话号码。这是 READ_PHONE_STATE 所授予权限的子集，但暴露给即时应用。'],
        'READ_VOICEMAIL': ['signature', '允许应用读取系统中的语音邮件。', '允许应用读取系统中的语音邮件。'],
        'REQUEST_COMPANION_RUN_IN_BACKGROUND': ['normal', '允许配套应用在后台运行。', '允许配套应用在后台运行。'],
        'REQUEST_COMPANION_USE_DATA_IN_BACKGROUND': ['normal', '允许配套应用在后台使用数据。', '允许配套应用在后台使用数据。'],
        'REQUEST_DELETE_PACKAGES': ['normal', '允许应用请求删除软件包。', '允许应用请求删除软件包。'],
        'REQUEST_IGNORE_BATTERY_OPTIMIZATIONS': ['normal', '用于调用 Settings.ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS 的权限。', '应用使用 Settings.ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS 所必须持有的权限。'],
        'SEND_RESPOND_VIA_MESSAGE': ['signatureOrSystem', '允许在通话期间发送"以消息回复"请求。', '允许应用（电话）在来电期间向其他应用发送请求以处理"以消息回复"操作。'],
        'TRANSMIT_IR': ['normal', '允许使用设备的红外发射器。', '允许使用设备的红外发射器（如可用）。'],
        'UNINSTALL_SHORTCUT': ['normal', '已弃用的卸载快捷方式权限。', '请勿在应用中使用此权限。该权限已不再受支持。'],
        'USE_BIOMETRIC': ['normal', '允许使用设备支持的生物识别方式。', '允许应用使用设备支持的生物识别方式。'],
        'USE_FINGERPRINT': ['normal', '允许使用指纹', '此常量在 API 级别 28 中已弃用。应用应改为请求 USE_BIOMETRIC。'],
        'WRITE_CALL_LOG': ['dangerous', '允许写入（但不能读取）用户的通话记录。', '允许应用写入（但不能读取）用户的通话记录数据。'],
        'WRITE_VOICEMAIL': ['signature', '允许修改和删除语音邮件。', '允许应用修改和删除系统中现有的语音邮件。'],
        'ACCESS_BACKGROUND_LOCATION': ['dangerous', '在后台访问位置', '允许应用在后台访问位置。'],
        'ACCESS_MEDIA_LOCATION': ['dangerous', '访问任何地理位置', '允许应用访问用户共享收藏中持久保存的任何地理位置。'],
        'ACTIVITY_RECOGNITION': ['dangerous', '允许应用识别身体活动', '允许应用识别身体活动。'],
        'BIND_CALL_REDIRECTION_SERVICE': ['signature', '通话转接服务进行系统绑定所需。', '通话转接服务必须要求此权限，以确保只有系统可以绑定到它。'],
        'BIND_CARRIER_MESSAGING_CLIENT_SERVICE': ['signature', '运营商消息客户端服务进行系统保护所需。', 'CarrierMessagingClientService 的子类必须使用此权限进行保护。'],
        'CALL_COMPANION_APP': ['normal', '允许 InCallService 应用充当通话配套应用。', '允许实现 InCallService API 的应用有资格被启用为通话配套应用。这意味着当有通话处于活动状态时，电信框架将绑定到该应用的 InCallService 实现。该应用可以使用 InCallService API 查看系统上通话的信息并控制这些通话。'],
        'REQUEST_PASSWORD_COMPLEXITY': ['normal', '允许请求并提示升级屏幕锁定复杂度。', '允许应用请求屏幕锁定复杂度，并提示用户将屏幕锁定更新到一定复杂度级别。'],
        'SMS_FINANCIAL_TRANSACTIONS': ['signature', '允许金融应用读取经过筛选的短信', '允许金融应用读取经过筛选的短信。保护级别：signature|appop。此常量在 API 级别 S 中已弃用。'],
        'START_VIEW_PERMISSION_USAGE': ['signature', '允许启动应用的权限使用情况界面。', '允许持有者启动应用的权限使用情况界面。'],
        'USE_FULL_SCREEN_INTENT': ['normal', '在通知中使用全屏 Intent 所需。', '面向 Build.VERSION_CODES.Q 且希望在通知中使用全屏 Intent 的应用所需。'],
        'ACCESS_CALL_AUDIO': ['signature', '应用可访问通话音频', '允许被分配到拨号器角色的应用访问电话通话的音频流（发送和接收）。'],
        'BIND_CONTROLS': ['signatureOrSystem', '允许 SystemUI 请求第三方控件。', '允许 SystemUI 请求第三方控件。仅应由系统请求，并由 ControlsProviderService 声明要求。'],
        'BIND_QUICK_ACCESS_WALLET_SERVICE': ['signature', '快捷访问钱包服务进行系统绑定所需。', '快捷访问钱包服务必须要求此权限，以确保只有系统可以绑定到它。'],
        'INTERACT_ACROSS_PROFILES': ['normal', '允许在同一组中的配置文件之间进行交互。', '允许在同一配置文件组中的配置文件之间进行交互。'],
        'LOADER_USAGE_STATS': ['signatureOrSystem', '允许数据加载器读取软件包访问日志。', '允许数据加载器读取软件包的访问日志。访问日志包含随时间推移所引用的页面集合。'],
        'MANAGE_EXTERNAL_STORAGE': ['dangerous', '允许应用在作用域存储中广泛访问外部存储', '允许应用在作用域存储中广泛访问外部存储。供需要代表用户管理文件的少数应用使用。'],
        'NFC_PREFERRED_PAYMENT_INFO': ['normal', '允许接收 NFC 首选支付服务信息。', '允许应用接收 NFC 首选支付服务信息。'],
        'QUERY_ALL_PACKAGES': ['normal', '允许查询设备上的任何普通应用。', '允许查询设备上的任何普通应用，无论其清单声明如何。'],
        'READ_PRECISE_PHONE_STATE': ['dangerous', '允许对精确手机状态的只读访问。', '允许对精确手机状态的只读访问。允许拨号器、运营商应用或 IMS 应用等特殊用途应用读取手机状态的详细信息。'],
        'READ_APP_BADGE': ['normal', '显示应用通知', '允许应用显示应用图标角标。'],
        'BIND_COMPANION_DEVICE_SERVICE': ['normal', '配套设备服务进行系统绑定所需。', '任何配套设备服务必须要求此权限，以确保只有系统可以绑定到它。'],
        'HIDE_OVERLAY_WINDOWS': ['normal', '防止非系统覆盖窗口', '允许应用防止非系统覆盖窗口绘制在其之上。'],
        'HIGH_SAMPLING_RATE_SENSORS': ['normal', '访问更高采样率的传感器数据', '允许应用访问采样率高于 200 Hz 的传感器数据。'],
        'MANAGE_ONGOING_CALLS': ['signature', '查询和管理进行中的通话详情', '允许查询进行中的通话详情并管理进行中的通话。'],
        'REQUEST_COMPANION_PROFILE_WATCH': ['normal', '允许与设备关联为"手表"。', '允许应用请求通过 CompanionDeviceManager 关联为"手表"设备。'],
        'REQUEST_OBSERVE_COMPANION_DEVICE_PRESENCE': ['normal', '允许订阅配套设备的在线状态通知。', '允许应用订阅其关联配套设备在线状态变化的通知。'],
        'SCHEDULE_EXACT_ALARM': ['normal', '允许为后台工作使用精确闹钟调度。', '允许应用使用精确闹钟调度 API 来执行对时间敏感的后台工作。'],
        'USE_ICC_AUTH_WITH_DEVICE_IDENTIFIER': ['signature', '允许读取设备标识符并使用基于 ICC 的身份验证。', '允许读取设备标识符并使用基于 ICC 的身份验证（如 EAP-AKA）。通常在访问运营商服务器和管理用户服务的身份验证中需要此权限。'],
        'ACCESS_BLOBS_ACROSS_USERS': ['normal', '允许跨用户访问数据 blob。', '允许应用跨用户访问数据 blob。'],
        'BIND_CREDENTIAL_PROVIDER_SERVICE': ['signature', '凭据提供者服务进行系统绑定所需。', '凭据提供者服务必须要求此权限，以确保只有系统可以绑定到它。'],
        'BIND_TV_INTERACTIVE_APP': ['signature', '电视交互式应用服务进行系统绑定所需。', '电视交互式应用服务必须要求此权限，以确保只有系统可以绑定到它。'],
        'BLUETOOTH_ADVERTISE': ['dangerous', '需要向附近的蓝牙设备进行广播。', '需要能够向附近的蓝牙设备进行广播。'],
        'BLUETOOTH_CONNECT': ['dangerous', '连接已配对蓝牙设备所必需。', '需要能够连接已配对的蓝牙设备。'],
        'BLUETOOTH_SCAN': ['dangerous', '发现和配对蓝牙设备所必需。', '需要能够发现并配对附近的蓝牙设备。'],
        'BODY_SENSORS_BACKGROUND': ['dangerous', '授予对身体传感器（如心率）的后台访问权限。', '允许应用访问用户用于测量身体内部状况的传感器数据，如心率。如果您请求此权限，则还必须请求 BODY_SENSORS。仅请求此权限本身不会授予您对身体传感器的访问权限。'],
        'CONFIGURE_WIFI_DISPLAY': ['normal', '允许配置和连接 Wi-Fi 显示器。', '允许应用配置和连接 Wi-Fi 显示器。'],
        'CREDENTIAL_MANAGER_QUERY_CANDIDATE_CREDENTIALS': ['normal', '允许查询凭据候选项的元数据。', '允许浏览器调用一组查询 API，以获取在 CredentialManager.prepareGetCredential API 期间准备的凭据候选项的元数据。'],
        'CREDENTIAL_MANAGER_SET_ALLOWED_PROVIDERS': ['normal', '允许指定候选取证提供者。', '允许指定在凭据管理器获取流程中要查询的候选取证提供者，或在凭据管理器创建流程中将其优先作为默认提供者。'],
        'CREDENTIAL_MANAGER_SET_ORIGIN': ['normal', '允许代表另一个 RP 调用凭据管理器 API。', '允许浏览器代表另一个 RP 调用凭据管理器 API。'],
        'DELIVER_COMPANION_MESSAGES': ['normal', '允许向系统传递配套消息。', '允许应用向系统传递配套消息。'],
        'DETECT_SCREEN_CAPTURE': ['normal', '在尝试截取应用窗口时通知。', '允许应用在其窗口被尝试截屏时获得通知。'],
        'ENFORCE_UPDATE_OWNERSHIP': ['normal', '表示有意通过 PackageInstaller 成为更新所有者。', '允许应用通过 PackageInstaller.SessionParams.setRequestUpdateOwnership(boolean) 表示其有意成为更新所有者。'],
        'EXECUTE_APP_ACTION': ['internal', '允许辅助应用在其他应用内执行操作。', '允许辅助应用代表用户在其他应用内执行操作。'],
        'FOREGROUND_SERVICE_CAMERA': ['normal', '允许带相机使用的前台服务。', '允许普通应用使用 Service.startForeground 且类型为"camera"。'],
        'FOREGROUND_SERVICE_CONNECTED_DEVICE': ['normal', '允许带已连接设备使用的前台服务。', '允许普通应用使用 Service.startForeground 且类型为"connectedDevice"。'],
        'FOREGROUND_SERVICE_DATA_SYNC': ['normal', '允许用于数据同步的前台服务。', '允许普通应用使用 Service.startForeground 且类型为"dataSync"。'],
        'FOREGROUND_SERVICE_HEALTH': ['normal', '允许带健康相关功能的前台服务。', '允许普通应用使用 Service.startForeground 且类型为"health"。'],
        'FOREGROUND_SERVICE_LOCATION': ['normal', '允许带位置使用的前台服务。', '允许普通应用使用 Service.startForeground 且类型为"location"。'],
        'FOREGROUND_SERVICE_MEDIA_PLAYBACK': ['normal', '允许用于媒体播放的前台服务。', '允许普通应用使用 Service.startForeground 且类型为"mediaPlayback"。'],
        'FOREGROUND_SERVICE_MEDIA_PROJECTION': ['normal', '允许用于媒体投影的前台服务。', '允许普通应用使用 Service.startForeground 且类型为"mediaProjection"。'],
        'FOREGROUND_SERVICE_MICROPHONE': ['normal', '允许带麦克风使用的前台服务。', '允许普通应用使用 Service.startForeground 且类型为"microphone"。'],
        'FOREGROUND_SERVICE_PHONE_CALL': ['normal', '允许在通话期间使用前台服务。', '允许普通应用使用 Service.startForeground 且类型为"phoneCall"。'],
        'FOREGROUND_SERVICE_REMOTE_MESSAGING': ['normal', '允许用于远程消息传递的前台服务。', '允许普通应用使用 Service.startForeground 且类型为"remoteMessaging"。'],
        'FOREGROUND_SERVICE_SPECIAL_USE': ['normal', '允许特殊用途的前台服务。', '允许普通应用使用 Service.startForeground 且类型为"specialUse"。'],
        'FOREGROUND_SERVICE_SYSTEM_EXEMPTED': ['normal', '允许系统豁免类型的前台服务。', '允许普通应用使用 Service.startForeground 且类型为"systemExempted"。应用只能在 ServiceInfo.FOREGROUND_SERVICE_TYPE_SYSTEM_EXEMPTED 中列出的用例中使用此类型。'],
        'LAUNCH_CAPTURE_CONTENT_ACTIVITY_FOR_NOTE': ['internal', '允许为截图捕获屏幕内容。', '允许应用捕获屏幕内容以使用 Intent 操作 Intent.ACTION_LAUNCH_CAPTURE_CONTENT_ACTIVITY_FOR_NOTE 执行截图。'],
        'LAUNCH_MULTI_PANE_SETTINGS_DEEP_LINK': ['normal', '允许在设置应用中嵌入显示 Activity。', '应用需要此权限以通过 Settings.ACTION_SETTINGS_EMBED_DEEP_LINK_ACTIVITY 将其 Activity 嵌入显示在设置应用中。'],
        'MANAGE_DEVICE_LOCK_STATE': ['internal', '允许融资设备 kiosk 应用与设备锁定服务交互。', '允许融资设备 kiosk 应用对设备锁定服务执行操作。'],
        'MANAGE_DEVICE_POLICY_ACCESSIBILITY': ['normal', '允许管理与无障碍相关的策略。', '允许应用管理与无障碍相关的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_ACCOUNT_MANAGEMENT': ['normal', '允许设置与账户管理相关的策略。', '允许应用设置与账户管理相关的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS。'],
        'MANAGE_DEVICE_POLICY_ACROSS_USERS': ['normal', '允许设置安全设备策略而无需访问用户数据。', '允许应用为当前用户之外的用户设置设备策略，这些策略是保护设备所有权所必需的，且无需访问用户数据。持有此权限可让设备上所有用户在符合不授予用户数据访问权限的条件下使用其他持有的 MANAGE_DEVICE_POLICY_* 权限。'],
        'MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL': ['normal', '允许设置可访问用户数据的设备策略。', '允许应用为当前用户之外的用户设置设备策略。是 MANAGE_DEVICE_POLICY_ACROSS_USERS 的更完整形式，移除了访问用户数据的限制。持有此权限可让设备上所有用户使用任何其他持有的 MANAGE_DEVICE_POLICY_* 权限。常量值："android.permission.MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL"'],
        'MANAGE_DEVICE_POLICY_ACROSS_USERS_SECURITY_CRITICAL': ['normal', '启用保护用户数据的关键安全策略。', '允许应用为当前用户之外的用户设置设备策略，这些策略对保护当前用户内的数据至关重要。持有此权限可让设备上所有用户在符合保护当前用户内数据所必需的条件下使用其他持有的 MANAGE_DEVICE_POLICY_* 权限。'],
        'MANAGE_DEVICE_POLICY_AIRPLANE_MODE': ['normal', '允许设置与飞行模式相关的策略。', '允许应用设置与飞行模式相关的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS。'],
        'MANAGE_DEVICE_POLICY_APPS_CONTROL': ['normal', '允许管理用于修改应用的策略。', '允许应用管理与修改应用相关的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_APP_RESTRICTIONS': ['normal', '允许管理应用限制。', '允许应用管理应用限制。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_APP_USER_DATA': ['normal', '允许为应用用户数据设置策略。', '允许应用管理与应用用户数据相关的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_AUDIO_OUTPUT': ['normal', '启用音频输出策略设置。', '允许应用设置与音频输出相关的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_AUTOFILL': ['normal', '允许为自动填充服务设置策略。', '允许应用设置与自动填充相关的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_BACKUP_SERVICE': ['normal', '允许管理备份服务策略。', '允许应用管理备份服务策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_BLUETOOTH': ['normal', '允许设置与蓝牙相关的策略。', '允许应用设置与蓝牙相关的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_BUGREPORT': ['normal', '允许在用户同意下请求错误报告。', '允许应用在用户同意的情况下请求错误报告。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_CALLS': ['normal', '允许管理电话通话策略。', '允许应用管理通话策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_CAMERA': ['normal', '允许设置相机使用策略。', '允许应用设置与限制用户使用或启用和禁用相机相关的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS。'],
        'MANAGE_DEVICE_POLICY_CERTIFICATES': ['normal', '允许管理证书策略。', '允许应用设置与证书相关的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_COMMON_CRITERIA_MODE': ['normal', '允许管理通用准则模式策略。', '允许应用管理与通用准则模式相关的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_DEBUGGING_FEATURES': ['normal', '允许管理调试功能策略。', '允许应用管理调试功能策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_DEFAULT_SMS': ['normal', '允许为默认短信应用设置策略。', '允许应用设置与默认短信应用相关的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS。'],
        'MANAGE_DEVICE_POLICY_DEVICE_IDENTIFIERS': ['normal', '允许管理设备标识符策略。', '允许应用管理与设备标识符相关的策略。'],
        'MANAGE_DEVICE_POLICY_DISPLAY': ['normal', '允许为显示管理设置策略。', '允许应用设置与显示相关的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_FACTORY_RESET': ['normal', '允许为恢复出厂设置设置策略。', '允许应用设置与恢复出厂设置相关的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_FUN': ['normal', '允许设置与娱乐活动相关的策略。', '允许应用设置与娱乐相关的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_INPUT_METHODS': ['normal', '允许设置输入法策略。', '允许应用设置与输入法相关的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS。'],
        'MANAGE_DEVICE_POLICY_INSTALL_UNKNOWN_SOURCES': ['normal', '允许设置从未知来源安装应用的策略。', '允许应用管理从未知来源安装的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 MANAGE_SECURITY_CRITICAL_DEVICE_POLICY_ACROSS_USERS。'],
        'MANAGE_DEVICE_POLICY_KEEP_UNINSTALLED_PACKAGES': ['normal', '允许按策略保留已卸载的软件包。', '允许应用设置与保留已卸载软件包相关的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_KEYGUARD': ['normal', '允许管理锁屏设置策略。', '允许应用管理与锁屏相关的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_SECURITY_CRITICAL。'],
        'MANAGE_DEVICE_POLICY_LOCALE': ['normal', '允许为语言环境管理设置策略。', '允许应用设置与语言环境相关的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_LOCATION': ['normal', '允许设置位置服务策略。', '允许应用设置与位置相关的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_LOCK': ['normal', '允许按策略锁定配置文件或设备。', '允许应用使用适当的跨用户权限锁定配置文件或设备。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_LOCK_CREDENTIALS': ['normal', '允许设置锁定凭据策略。', '允许应用设置与锁定凭据相关的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_SECURITY_CRITICAL。'],
        'MANAGE_DEVICE_POLICY_LOCK_TASK': ['normal', '允许管理锁任务策略。', '允许应用管理锁任务策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_METERED_DATA': ['normal', '允许管理按流量计费数据的策略。', '允许应用管理与按流量计费数据相关的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_MICROPHONE': ['normal', '允许设置麦克风使用策略。', '允许应用设置与限制用户使用或启用和禁用麦克风相关的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS。'],
        'MANAGE_DEVICE_POLICY_MOBILE_NETWORK': ['normal', '允许设置移动网络策略。', '允许应用设置与移动网络相关的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_MODIFY_USERS': ['normal', '允许管理策略以防止用户修改。', '允许应用管理防止用户修改用户的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_MTE': ['normal', '允许管理内存标记扩展（MTE）策略。', '允许应用管理与内存标记扩展（MTE）相关的策略。'],
        'MANAGE_DEVICE_POLICY_NEARBY_COMMUNICATION': ['normal', '允许设置附近通信策略。', '允许应用设置与附近通信相关的策略（例如 Beam 和附近流传输）。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_NETWORK_LOGGING': ['normal', '允许设置网络日志记录策略。', '允许应用设置与网络日志记录相关的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_ORGANIZATION_IDENTITY': ['normal', '允许管理设备管理组织的身份。', '允许应用管理设备管理组织的身份。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_OVERRIDE_APN': ['normal', '允许设置覆盖 APN 的策略。', '允许应用设置与覆盖 APN 相关的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_PACKAGE_STATE': ['normal', '允许设置隐藏和挂起软件包的策略。', '允许应用设置与隐藏和挂起软件包相关的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS。'],
        'MANAGE_DEVICE_POLICY_PHYSICAL_MEDIA': ['normal', '允许为物理介质使用设置策略。', '允许应用设置与物理介质相关的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_PRINTING': ['normal', '允许为打印服务设置策略。', '允许应用设置与打印相关的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_PRIVATE_DNS': ['normal', '允许为私有 DNS 管理设置策略。', '允许应用设置与私有 DNS 相关的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_PROFILES': ['normal', '允许为用户配置文件设置策略。', '允许应用设置与配置文件相关的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_PROFILE_INTERACTION': ['normal', '允许为用户配置文件之间的交互设置策略。', '允许应用设置与配置文件交互相关的策略（例如禁止跨配置文件复制和粘贴）。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_PROXY': ['normal', '允许独立于网络设置全局 HTTP 代理。', '允许应用设置与网络无关的全局 HTTP 代理。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_QUERY_SYSTEM_UPDATES': ['normal', '允许查询系统更新。', '允许应用查询系统更新。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_RESET_PASSWORD': ['normal', '允许强制设置新的设备解锁密码或配置文件挑战。', '允许应用在当前用户上强制设置新的设备解锁密码或托管配置文件挑战。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_RESTRICT_PRIVATE_DNS': ['normal', '允许限制用户对私有 DNS 的配置。', '允许应用设置与限制用户配置私有 DNS 相关的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS。'],
        'MANAGE_DEVICE_POLICY_RUNTIME_PERMISSIONS': ['normal', '允许为软件包设置运行时权限。', '允许应用设置软件包上运行时权限的授予状态。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_RUN_IN_BACKGROUND': ['normal', '允许为后台进程管理设置策略。', '允许应用设置与后台运行用户相关的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_SAFE_BOOT': ['normal', '允许管理安全启动模式策略。', '允许应用管理安全启动策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_SCREEN_CAPTURE': ['normal', '允许为截屏功能设置策略。', '允许应用设置与截屏相关的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS。'],
        'MANAGE_DEVICE_POLICY_SCREEN_CONTENT': ['normal', '允许为屏幕内容使用设置策略。', '允许应用设置与屏幕内容使用相关的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_SECURITY_LOGGING': ['normal', '允许为安全日志记录设置策略。', '允许应用设置与安全日志记录相关的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_SETTINGS': ['normal', '允许设置常规设备策略。', '允许应用设置与设置相关的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_SMS': ['normal', '允许为短信功能设置策略。', '允许应用设置与短信相关的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_STATUS_BAR': ['normal', '允许为状态栏设置策略。', '允许应用设置与状态栏相关的策略。'],
        'MANAGE_DEVICE_POLICY_SUPPORT_MESSAGE': ['normal', '允许为受策略影响的操作设置支持消息。', '允许应用在用户操作受活动策略影响时设置支持消息。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_SUSPEND_PERSONAL_APPS': ['normal', '允许通过策略设置挂起个人应用。', '允许应用设置与挂起个人应用相关的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_SYSTEM_APPS': ['normal', '允许管理与系统应用相关的策略。', '允许应用管理与系统应用相关的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_SYSTEM_DIALOGS': ['normal', '允许为系统对话框设置策略。', '允许应用设置与系统对话框相关的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_SYSTEM_UPDATES': ['normal', '允许为系统更新设置策略。', '允许应用设置与系统更新相关的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_TIME': ['normal', '允许管理与时间设置相关的策略。', '允许应用管理与时间相关的设备策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_USB_DATA_SIGNALLING': ['normal', '允许为 USB 数据信令设置策略。', '允许应用设置与 USB 数据信令相关的策略。'],
        'MANAGE_DEVICE_POLICY_USB_FILE_TRANSFER': ['normal', '允许为 USB 文件传输设置策略。', '允许应用设置与 USB 文件传输相关的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_USERS': ['normal', '允许设置与用户管理相关的策略。', '允许应用设置与用户相关的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_VPN': ['normal', '允许为 VPN 使用设置策略。', '允许应用设置与 VPN 相关的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_WALLPAPER': ['normal', '允许为壁纸管理设置策略。', '允许应用设置与壁纸相关的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_WIFI': ['normal', '允许为 WiFi 连接设置策略。', '允许应用设置与 WiFi 相关的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS。'],
        'MANAGE_DEVICE_POLICY_WINDOWS': ['normal', '允许为窗口管理设置策略。', '允许应用设置与窗口相关的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_WIPE_DATA': ['normal', '允许管理数据擦除策略。', '允许应用管理与擦除数据相关的策略。要在非调用方的其他用户上调用此权限保护的 API，需要 Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS。'],
        'MANAGE_MEDIA': ['signature', '允许在未经用户确认的情况下修改和删除媒体文件。', '允许应用在未经用户确认的情况下修改和删除本设备或任何连接的存储设备上的媒体文件。此权限生效的前提是应用已被授予 READ_EXTERNAL_STORAGE 或 MANAGE_EXTERNAL_STORAGE 权限。'],
        'MANAGE_WIFI_INTERFACES': ['normal', '允许管理 Wi-Fi 接口请求之间的冲突。', '允许应用在 Wi-Fi 接口请求无法在不拆除一个或多个其他接口的情况下被满足时获得通知，并提供批准或拒绝该请求的决定。第三方应用不可使用。'],
        'MANAGE_WIFI_NETWORK_SELECTION': ['normal', '允许对 Wi-Fi 网络选择进行特权管理。', '此权限用于让 OEM 厂商授予其受信任的应用对一部分特权 Wi-Fi API 的访问权限，以提升 Wi-Fi 性能。允许应用管理与 Wi-Fi 网络选择相关的功能，例如启用或禁用全局自动连接、修改连接扫描间隔以及批准 Wi-Fi Direct 连接。第三方应用不可使用。'],
        'NEARBY_WIFI_DEVICES': ['dangerous', '通过 Wi-Fi 向附近设备广播和连接所必需。', '需要能够通过 Wi-Fi 向附近设备进行广播和连接。'],
        'OVERRIDE_WIFI_CONFIG': ['normal', '允许修改任何 Wi-Fi 配置。', '允许应用修改任何 Wi-Fi 配置，即使是由其他应用创建的。重新配置后，原始创建者将无法再进行任何修改。第三方应用不可使用。'],
        'POST_NOTIFICATIONS': ['dangerous', '允许应用发布通知。', '允许应用发布通知。'],
        'PROVIDE_OWN_AUTOFILL_SUGGESTIONS': ['internal', '允许使用自动填充框架提供自动填充建议。', '允许应用使用自动填充框架展示其建议。'],
        'PROVIDE_REMOTE_CREDENTIALS': ['signature', '允许从远程设备存储和检索凭据。', '允许应用能够从远程设备存储和检索凭据。'],
        'READ_ASSISTANT_APP_SEARCH_DATA': ['normal', '允许查询对 Assistant 角色可见的全局 AppSearch 数据。', '允许应用查询 AppSearch 中对 ASSISTANT 角色可见的全局数据。'],
        'READ_BASIC_PHONE_STATE': ['normal', '允许对基本手机状态信息的只读访问。', '允许以非危险权限对手机状态进行只读访问，包括蜂窝网络类型、软件版本等信息。'],
        'READ_HOME_APP_SEARCH_DATA': ['normal', '允许查询对 Home 角色可见的全局 AppSearch 数据。', '允许应用查询 AppSearch 中对 HOME 角色可见的全局数据。'],
        'READ_MEDIA_AUDIO': ['dangerous', '允许从外部存储读取音频文件。', '允许应用从外部存储读取音频文件。'],
        'READ_MEDIA_IMAGES': ['dangerous', '允许从外部存储读取图片文件。', '允许应用从外部存储读取图片文件。'],
        'READ_MEDIA_VIDEO': ['dangerous', '允许从外部存储读取视频文件。', '允许应用从外部存储读取视频文件。'],
        'READ_MEDIA_VISUAL_USER_SELECTED': ['dangerous', '允许读取用户在外部存储中选择的图片或视频文件。', '允许应用读取用户通过权限提示照片选择器从外部存储中选择的图片或视频文件。应用可以检查此权限以验证用户已决定使用照片选择器，而非授予对 READ_MEDIA_IMAGES 或 READ_MEDIA_VIDEO 的访问权限。这不会阻止应用手动访问标准照片选择器。此权限应根据所需的媒体类型与 READ_MEDIA_IMAGES 和/或 READ_MEDIA_VIDEO 一起请求。'],
        'READ_NEARBY_STREAMING_POLICY': ['normal', '允许读取附近流传输策略设置。', '允许应用读取附近流传输策略。该策略控制是否允许设备将其通知和应用流传输到附近设备。非设备所有者的应用需要此权限才能调用 DevicePolicyManager.getNearbyNotificationStreamingPolicy() 或 DevicePolicyManager.getNearbyAppStreamingPolicy()。'],
        'REQUEST_COMPANION_PROFILE_APP_STREAMING': ['normal', '允许请求与应用流传输的虚拟显示关联。', '允许应用请求通过 CompanionDeviceManager 与能够流传输 Android 应用的虚拟显示器（AssociationRequest.DEVICE_PROFILE_APP_STREAMING）相关联。第三方应用不可使用。'],
        'REQUEST_COMPANION_PROFILE_AUTOMOTIVE_PROJECTION': ['normal', '允许请求与车载主机关联以进行汽车投影。', '允许应用请求通过 CompanionDeviceManager 与支持汽车投影的车载主机（AssociationRequest.DEVICE_PROFILE_AUTOMOTIVE_PROJECTION）相关联。第三方应用不可使用。'],
        'REQUEST_COMPANION_PROFILE_COMPUTER': ['normal', '允许请求与计算机关联以共享功能。', '允许应用请求通过 CompanionDeviceManager 与计算机相关联，以与其他设备共享功能和/或数据，例如通知、照片和媒体（AssociationRequest.DEVICE_PROFILE_COMPUTER）。第三方应用不可使用。'],
        'REQUEST_COMPANION_PROFILE_GLASSES': ['normal', '允许请求与设备关联为"眼镜"。', '允许应用请求通过 CompanionDeviceManager 关联为"眼镜"设备。'],
        'REQUEST_COMPANION_PROFILE_NEARBY_DEVICE_STREAMING': ['normal', '允许请求将内容流传输到附近设备。', '允许应用请求通过 CompanionDeviceManager 将内容从 Android 主机流传输到附近设备（AssociationRequest.DEVICE_PROFILE_NEARBY_DEVICE_STREAMING）。第三方应用不可使用。'],
        'REQUEST_COMPANION_SELF_MANAGED': ['normal', '允许创建自管理配套设备关联。', '允许应用创建"自管理"关联。'],
        'REQUEST_COMPANION_START_FOREGROUND_SERVICES_FROM_BACKGROUND': ['normal', '允许配套应用从后台启动前台服务。', '允许配套应用从后台启动前台服务。'],
        'RUN_USER_INITIATED_JOBS': ['normal', '允许使用用户发起的作业 API。', '允许应用使用用户发起的作业 API。更多详情请参见 JobInfo.Builder.setUserInitiated(boolean)。'],
        'START_FOREGROUND_SERVICES_FROM_BACKGROUND': ['normal', '允许从后台启动前台服务。', '允许应用随时从后台启动前台服务。此权限不供第三方应用使用，唯一例外是该应用是默认短信应用。否则，它仅供特权应用、应用验证器应用以及具有 EMERGENCY 或 SYSTEM GALLERY 角色的应用使用。'],
        'START_VIEW_APP_FEATURES': ['signature', '允许启动列出应用功能的界面。', '允许持有者启动显示应用功能列表的界面。'],
        'SUBSCRIBE_TO_KEYGUARD_LOCKED_STATE': ['signature', '允许订阅锁屏锁定状态。', '允许应用订阅锁屏锁定（即显示）状态。'],
        'TURN_SCREEN_ON': ['normal', '允许点亮屏幕，供家庭自动化应用使用。', '允许应用点亮屏幕，例如使用 PowerManager.ACQUIRE_CAUSES_WAKEUP。仅供家庭自动化应用使用。'],
        'UPDATE_PACKAGES_WITHOUT_USER_ACTION': ['normal', '允许在不要求用户操作的情况下更新软件包。', '允许应用通过 PackageInstaller.SessionParams.setRequireUserAction(int) 表明应用更新不需要用户操作。'],
        'USE_EXACT_ALARM': ['normal', '允许在无需用户权限的情况下使用精确闹钟。', '允许应用像使用 SCHEDULE_EXACT_ALARM 一样使用精确闹钟，但无需向用户请求此权限。此权限仅供依赖精确闹钟作为其核心功能的应用使用。如果您的应用需要精确闹钟作为用户可能使用也可能不使用的次要功能，则应继续使用 SCHEDULE_EXACT_ALARM。请注意，这是一个强大的权限，应用商店可能会强制执行审核政策以审计和审查此权限的使用情况。如果发现应用滥用此权限，此类审核可能涉及从应用商店下架。'],
        'UWB_RANGING': ['dangerous', '使用超宽带（UWB）测距所必需。', '需要能够使用超宽带（UWB）测距设备。'],
        'ACCESS_HIDDEN_PROFILES': ['normal', '通过声明 ACCESS_HIDDEN_PROFILES 权限来支持私密空间。', '允许应用访问具有 android.content.pm.UserProperties#PROFILE_API_VISIBILITY_HIDDEN 用户属性的配置文件，例如 UserManager.USER_TYPE_PROFILE_PRIVATE。'],
        'BIND_APP_FUNCTION_SERVICE': ['signature', 'AppFunctionService 必须要求此权限，以确保只有系统可以绑定到它。', 'AppFunctionService 必须要求此权限，以确保只有系统可以绑定到它。'],
        'FOREGROUND_SERVICE_MEDIA_PROCESSING': ['normal', '允许普通应用使用 Service.startForeground 且类型为"mediaProcessing"。', '允许普通应用使用 Service.startForeground 且类型为"mediaProcessing"。'],
        'MANAGE_DEVICE_POLICY_ASSIST_CONTENT': ['internal', '授予应用配置用于与特权应用（如 Assistant 应用）共享辅助内容的策略的权限。', '允许应用设置与将辅助内容发送给特权应用（如 Assistant 应用）相关的策略。'],
        'DETECT_SCREEN_RECORDING': ['normal', '授予应用在音频或屏幕录制进行时接收通知的权限。', '允许应用在自身被录制时获得通知。'],
        'MANAGE_DEVICE_POLICY_BLOCK_UNINSTALL': ['internal', '允许应用控制防止特定软件包被卸载的策略。', '允许应用管理与阻止软件包卸载相关的策略。'],
        'MANAGE_DEVICE_POLICY_CAMERA_TOGGLE': ['internal', '允许应用强制执行控制相机开关状态的策略。', '允许应用管理与相机开关相关的策略。'],
        'MANAGE_DEVICE_POLICY_CONTENT_PROTECTION': ['internal', '授予应用强制执行限制指定软件包卸载的策略的权限。', '允许应用管理与内容保护相关的策略。'],
        'MANAGE_DEVICE_POLICY_MANAGED_SUBSCRIPTIONS': ['internal', '授予应用配置管理由管理员下载的订阅的策略的权限。', '允许应用设置与管理员下载的订阅相关的策略。'],
        'MANAGE_DEVICE_POLICY_MICROPHONE_TOGGLE': ['internal', '授予应用控制管理麦克风开关状态策略的权限。', '允许应用管理与麦克风开关相关的策略。'],
        'MEDIA_ROUTING_CONTROL': ['normal', '允许应用管理媒体应用的路由，仅限 COMPANION_DEVICE_WATCH 角色使用。', '允许应用控制媒体应用的路由。仅供 COMPANION_DEVICE_WATCH 角色使用。'],
        'READ_DROPBOX_DATA': ['normal', '允许应用访问 Dropbox 中存储的数据，仅供系统级或第一方应用使用，第三方应用不可用。', '允许应用访问 Dropbox 中的数据。第三方应用不可使用。'],
        'SET_BIOMETRIC_DIALOG_ADVANCED': ['normal', '允许应用自定义 BiometricDialog 功能（包括 Logo 和内容视图），仅限系统使用。', '允许应用设置 BiometricDialog（SystemUI）上的高级功能，包括 Logo、Logo 描述和带"更多选项"按钮的内容视图。第三方应用不可使用。'],
        'ACCESS_ORIENTATION': ['normal', '允许应用访问设备的方向。', '允许应用访问设备的方向。'],
        'ACCESS_LAUNCHER_DATA': ['normal', '管理主屏幕元数据和快捷方式', '此权限保护主屏幕/启动器应用中的内容提供者，使其能够管理主屏幕元数据，例如快捷方式放置、启动 Intent 和标签。'],
        'APPLY_PICTURE_PROFILE': ['normal', '将媒体质量配置文件应用于视频图层', '允许应用通过 MediaCodec.PARAMETER_KEY_PICTURE_PROFILE 将 MediaQualityManager.PictureProfile 应用于图层，此外系统应用还可以通过 SurfaceControl.Transaction#setPictureProfileHandle 应用。'],
        'BIND_TV_AD_SERVICE': ['signature', '绑定到电视广告服务', 'android.media.tv.ad.TvAdService 必须要求此权限，以确保只有系统可以绑定到它。'],
        'CAPTURE_KEYBOARD': ['normal', '在系统处理之前捕获键盘输入', '允许应用在 Android 系统有机会处理系统按键和快捷键之前捕获按键。'],
        'EXECUTE_APP_FUNCTIONS': ['normal', '代表用户执行功能', '允许应用代表用户在其他应用内执行操作。'],
        'MANAGE_DEVICE_POLICY_APP_FUNCTIONS': ['internal', '管理应用功能策略', '允许应用管理与 AppFunctions 相关的策略。'],
        'MANAGE_DEVICE_POLICY_THREAD_NETWORK': ['internal', '管理 Thread 网络策略', '允许应用设置与 Thread 网络相关的策略。'],
        'POST_PROMOTED_NOTIFICATIONS': ['normal', '发布推广通知', '应用发布推广通知所必需。'],
        'QUERY_ADVANCED_PROTECTION_MODE': ['normal', '查询高级保护模式状态', '允许应用查询设备的高级保护模式状态。'],
        'RANGING': ['dangerous', '测距附近设备', '需要能够使用通用测距模块对设备进行测距。'],
        'READ_COLOR_ZONES': ['normal', '读取屏幕色彩区域以用于环境照明', '允许应用读取屏幕上聚合的色彩区域，用于电视环境背光灯等用例。'],
        'READ_SYSTEM_PREFERENCES': ['normal', '读取系统设置和首选项', '允许应用访问设置首选项服务，以读取系统设置应用及向设置应用贡献设置的系统应用所暴露的设置。这允许调用应用通过宿主应用读取设置值，无需了解底层存储。'],
        'RECEIVE_SENSITIVE_NOTIFICATIONS': ['signature', '接收敏感通知内容', '允许具有 NotificationListenerService 的应用接收包含敏感信息的通知。'],
        'REQUEST_OBSERVE_DEVICE_UUID_PRESENCE': ['normal', '通过 UUID 观察附近设备的在线状态', '允许应用订阅基于 UUID 的附近设备在线状态变化通知。第三方应用不可使用。'],
        'TV_IMPLICIT_ENTER_PIP': ['normal', '隐式进入画中画模式', '允许应用在用户未明确请求时进入画中画模式。这包括使用 PictureInPictureParams.Builder#setAutoEnterEnabled 以及 Activity#onUserLeaveHint 和 Activity#onPause 等生命周期方法，在用户离开应用时进入画中画。此权限仅应用于特定的画中画使用类型。'],
        'WRITE_SYSTEM_PREFERENCES': ['normal', '写入系统设置和首选项', '允许应用访问设置首选项服务，以写入系统设置应用及向设置应用贡献设置的系统应用所暴露的设置值。这允许调用应用通过宿主应用写入设置值，无需了解底层存储。'],
    },

    'SPECIAL_PERMISSIONS': {
        'com.sec.android.provider.badge.permission.READ': ['normal', '在应用上显示通知数量', '在三星手机的应用启动图标上显示通知数量或角标。'],
        'com.sec.android.provider.badge.permission.WRITE': ['normal', '在应用上显示通知数量', '在三星手机的应用启动图标上显示通知数量或角标。'],
        'com.htc.launcher.permission.READ_SETTINGS': ['normal', '在应用上显示通知数量', '在 HTC 手机的应用启动图标上显示通知数量或角标。'],
        'com.htc.launcher.permission.UPDATE_SHORTCUT': ['normal', '在应用上显示通知数量', '在 HTC 手机的应用启动图标上显示通知数量或角标。'],
        'com.sonyericsson.home.permission.BROADCAST_BADGE': ['normal', '在应用上显示通知数量', '在索尼手机的应用启动图标上显示通知数量或角标。'],
        'com.sonymobile.home.permission.PROVIDER_INSERT_BADGE': ['normal', '在应用上显示通知数量', '在索尼手机的应用启动图标上显示通知数量或角标。'],
        'com.anddoes.launcher.permission.UPDATE_COUNT': ['normal', '在应用上显示通知数量', '在 Apex 启动器的应用启动图标上显示通知数量或角标。'],
        'com.majeur.launcher.permission.UPDATE_BADGE': ['normal', '在应用上显示通知数量', '在 Solid 启动器的应用启动图标上显示通知数量或角标。'],
        'com.huawei.android.launcher.permission.READ_SETTINGS': ['normal', '在应用上显示通知数量', '在华为手机的应用启动图标上显示通知数量或角标。'],
        'com.huawei.android.launcher.permission.WRITE_SETTINGS': ['normal', '在应用上显示通知数量', '在华为手机的应用启动图标上显示通知数量或角标。'],
        'com.huawei.android.launcher.permission.CHANGE_BADGE': ['normal', '在应用上显示通知数量', '在华为手机的应用启动图标上显示通知数量或角标。'],
        'com.oppo.launcher.permission.READ_SETTINGS': ['normal', '在应用上显示通知数量', '在 OPPO 手机的应用启动图标上显示通知数量或角标。'],
        'com.oppo.launcher.permission.WRITE_SETTINGS': ['normal', '在应用上显示通知数量', '在 OPPO 手机的应用启动图标上显示通知数量或角标。'],
        'com.google.android.gms.permission.AD_ID': ['normal', '应用展示广告', '该应用使用 Google 广告 ID，可能会投放广告。'],
        'com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE': ['normal', 'Google 定义的权限', '由 Google 定义的特殊权限。'],
        'com.google.android.c2dm.permission.RECEIVE': ['normal', '接收推送通知', '允许应用从云端接收推送通知。'],
        'com.android.vending.BILLING': ['normal', '应用提供应用内购买', '允许应用通过 Google Play 进行应用内购买。'],
        'android.permission.ACCESS_ADSERVICES_TOPICS': ['normal', '允许应用访问广告服务主题', '允许应用检索与广告主题或兴趣相关的信息，可用于定向广告。'],
        'android.permission.ACCESS_ADSERVICES_ATTRIBUTION': ['normal', '允许应用访问广告服务归因', '允许应用检索与广告归因相关的信息，可用于定向广告。应用可以收集用户如何与广告互动的数据（如点击或展示），以衡量广告活动的效果。'],
        'android.permission.ACCESS_ADSERVICES_AD_ID': ['normal', '允许应用访问设备的广告 ID。', '该 ID 是 Google 广告服务提供的唯一、用户可重置的标识符，允许应用在保护用户隐私的同时出于广告目的跟踪用户行为。'],
        'oppo.permission.OPPO_COMPONENT_SAFE': ['signature', 'OPPO 设备特定的权限', '用于授予应用访问某些出于安全原因而受限的系统级功能或组件的能力。该权限确保只有受信任的应用才能与 OPPO 系统的敏感部分交互。'],
        'com.huawei.permission.external_app_settings.USE_COMPONENT': ['signature', '华为设备特定的权限', '用于授予应用访问某些出于安全原因而受限的系统级功能或组件的能力。该权限确保只有受信任的应用才能与华为系统的敏感部分交互。'],

    },

    'MANIFEST_PERMISSION_GROUP': {
        'ACCOUNTS': '用于直接访问由账户管理器管理的账户的权限。',
        'COST_MONEY': '用于可使用户在无直接参与的情况下花费金钱的权限。',
        'DEVELOPMENT_TOOLS': '与开发功能相关的权限组。',
        'HARDWARE_CONTROLS': '用于提供对设备硬件直接访问的权限。',
        'LOCATION': '用于允许访问用户当前位置的权限。',
        'MESSAGES': '用于允许应用代表用户发送消息或拦截用户正在接收的消息的权限。',
        'NETWORK': '用于提供对网络服务访问权限的权限。',
        'PERSONAL_INFO': '用于提供对用户私人数据访问权限的权限，例如联系人、日历事件、电子邮件等。',
        'PHONE_CALLS': '用于与访问和修改电话状态相关的权限：拦截拨出电话、读取和修改电话状态。',
        'STORAGE': '与 SD 卡访问相关的权限组。',
        'SYSTEM_TOOLS': '与系统 API 相关的权限组。',
    },
}
